apiVersion: k3d.io/v1alpha5
kind: Simple
# metadata:
  # name: demo
servers: 1
agents: 2
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
image: rancher/k3s:v1.31.4-k3s1
volumes:
- volume: /tmp/somepath:/tmp/somepath
  nodeFilters:
  - all
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:8443:443
  nodeFilters:
  - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
    nodeLabels: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: ""
    serversMemory: ""
    agentsMemory: ""
